apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wikijs.fullname" . }}
  labels:
    {{- include "wikijs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wikijs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wikijs.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          envFrom:
            - secretRef:
               name: {{ include "wikijs.fullname" . }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          #resources:
          #  {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /wiki/config.yml
            name: config-volume
            subPath: config.yml
            readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "wikijs.fullname" . }}