apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wikijs.fullname" . }}
data:
      DB_TYPE: {{ .Values.dbConnect.dbType | b64enc }}
      DB_HOST: {{ .Values.dbConnect.dbHost | b64enc }}
      DB_PORT: {{ .Values.dbConnect.dbPort | quote | b64enc }}
      DB_USER: {{ .Values.dbConnect.dbUser | b64enc }}
      DB_PASS: {{ .Values.dbConnect.dbPass | b64enc }}
      DB_NAME: {{ .Values.dbConnect.dbName | b64enc }}